# Generated by Django 5.2.14 on 2026-05-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
